config/routes.rb
Rails.application.routes.draw do

  root 'game_sessions#new'
  resource :game_session, only: [:new, :create, :destroy]
  resources :games, only: [:show] do
    resources :rounds, :controller => 'games/rounds', only: [:show]
  end

  get '/welcome' => 'welcome#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :rounds
end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_game
    if cookies[:game_id]
      game_id = cookies.signed[:game_id]
      @current_game = Game.find_by_id(game_id)
    end
  end

  helper_method :current_game

end

app/controllers/game_sessions_controller.rb
class GameSessionsController < ApplicationController

  def new
  end

  def create
    game = Game.create(game_session_params)
    cookies.signed[:game_id] = game.id
    redirect_to welcome_path
  end

  def destroy
    cookies.delete(:game_id)
    redirect_to welcome_path
  end

  private

  def game_session_params
    params.require(:game_session).permit(:starting_actor)
  end

end

app/controllers/games/rounds_controller.rb
class Games::RoundsController < ApplicationController
  def show
    @round = Game.find(params[:game_id])
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def show
    @game = Game.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  def show
    if params[:actor]
      actor_name = params[:actor]
      # actor_imdb_id = FreebaseApi.get_actor_details(actor_name)
      # @actor_image = ImdbActorImageScraper.scrape_actor_image(actor_imdb_id)

      # Cuba Gooding, Jr. on FreebaseApi VS Cuba Gooding Jr. in Rotten Tomatoes
      @actor_image = ActorImageScraper.scrape_actor_image(actor_name)
      @actor = actor_name
      @movies = FreebaseApi.get_actor_movies(actor_name)
    else
      # movie_imdb_id = FreebaseApi.get_movie_thumbnail(movie_title)
      # @movie_poster_image = MoviePosterScraper.scrape_movie_poster(movie_imdb_id)

      ### TODO Move all this stuff into the RottenTomatoes Api
      rt_movie_object = RottenTomatoesApi.search(params[:movie])
      rt_movie_id = rt_movie_object["movies"].first["id"]
      @rt_actors = RottenTomatoesApi.get_movie_cast(rt_movie_id)["cast"].collect { |actor| actor["name"] }

      #### Sometimes Freebase gives you a better list of actors than Rotten Tomatoes.
      #### It might be worth having logic to just default to the one that has more.
      #### Or just stick with Rotten Tomatoes for now since then I can just rely on their search algorithm.
      #### Since they will favor more popular titles...like the new Dawn of the Dead / Godzilla

      @movie_poster_image = rt_movie_object["movies"].first["posters"]["original"].gsub("tmb", "det") if rt_movie_object["movies"]
      movie_title = params[:movie]
      @movie = movie_title
      @actors = FreebaseApi.get_movie_cast(movie_title)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_sessions_helper.rb
module GameSessionsHelper
end

app/helpers/games/rounds_helper.rb
module Games::RoundsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/game_sessions/new.html.erb
<%= form_for(:game_session, url: game_session_path) do |form| %>
  <div>
    <%= form.label :starting_actor %>
    <%= form.text_field :starting_actor %>
  </div>
  <%= form.submit "Start New Game!" %>
<% end %>

app/views/games/show.html.erb
<%= @game.starting_actor %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>A-Lister</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h2>Welcome to A-Lister!</h2>


<h3>search for an actor's movies:</h3>
<%= form_tag("/welcome", method: "get") do %>
  <div>
      <%= text_field_tag(:actor, nil) %>
      <%= submit_tag("Search") %>
  </div>
<% end %>

<h3>search for an movie's cast:</h3>
<%= form_tag("/welcome", method: "get") do %>
  <div>
      <%= text_field_tag(:movie, nil) %>
      <%= submit_tag("Search") %>
  </div>
<% end %>

app/views/welcome/show.html.erb
<% if @movies  %>
  <%= "Movies that #{@actor.titleize} has performed in:" %>
  <img src="<%= @actor_image %>" style="display: block;">
  <ul>
    <% @movies.each do |movie| %>
      <li><%= movie.html_safe %></li>
    <% end %>
  </ul>
<% end %>


<% if @rt_actors  %>
  <%= "The cast of #{@movie.titleize}:"%>
  <img src="<%= @movie_poster_image %>" style="display: block;">
  <ul>
    <% @rt_actors.each do |actor| %>
      <li><%= actor.html_safe %></li>
    <% end %>
  </ul>
<% end %>

<% if @actors  %>
  <%= "The cast of #{@movie.titleize}: FROM FREEBASE"%>
  <img src="<%= @movie_poster_image %>" style="display: block;">
  <ul>
    <% @actors.each do |actor| %>
      <li><%= actor.html_safe %></li>
    <% end %>
  </ul>
<% end %>